// Code generated by "stringer -type=resType"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[megacredit-0]
	_ = x[iron-1]
	_ = x[titanium-2]
	_ = x[plant-3]
	_ = x[energy-4]
	_ = x[heat-5]
	_ = x[resSize-6]
}

const _resType_name = "megacreditirontitaniumplantenergyheatresSize"

var _resType_index = [...]uint8{0, 10, 14, 22, 27, 33, 37, 44}

func (i resType) String() string {
	if i < 0 || i >= resType(len(_resType_index)-1) {
		return "resType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _resType_name[_resType_index[i]:_resType_index[i+1]]
}
